### ISSUE TITLE
v0.6 already starts TzWorld.Backend.DetsWithIndexCache

### ISSUE THREAD

**Issue by dvic** [kipcole9/astro#1]
Hi,

I noticed that the upgrade to v0.6 fails because `TzWorld.Backend.DetsWithIndexCache` is now started by astro itself. Is this intended? If so we need to update the docs/README :)

**Comment by kipcole9** [comment]
Thanks for the report. I've brought the code inline with the documentation. Configuring the supervisor tree should be done in the consuming application.  [Astro version 0.7.0](https://hex.pm/packages/astro/0.7.0) has been published. The changelog entry is:

### Bug Fixes

* Revert `Astro` back to a pure library application. The supervisor for `TzWorld` still needs to be started. This fix brings the code back into line with the [README](/readme.html). Thanks to @dvic for the report. Closes #1.

**Comment by kipcole9** [comment]
Thanks too for giving `Astro` a try. Feedback, suggestions and bug reports very welcome. I will add moonrise and moonset in the next couple of weeks but beyond that I will likely drive development based on user requirement.   Assuming I very limited mathematics and astronomy abilities allow me to!
